using System;
using CoreFoundation;
using Foundation;
using ObjCRuntime;
using Security;

namespace MessageTest
{
    // @protocol DoSomthingClassDelegate <NSObject>
    [Protocol, Model(AutoGeneratedName = true)]
    [BaseType(typeof(NSObject))]
    interface DoSomthingClassDelegate
    {
        // @required -(void)callBackFromTestLib;
        [Abstract]
        [Export("callBackFromTestLib")]
        void CallBackFromTestLib();
    }

    // @interface DoSomthingClass : NSObject
    [BaseType(typeof(NSObject))]
    [Protocol]
    interface DoSomthingClass
    {
        [Wrap("WeakDelegate")]
        DoSomthingClassDelegate Delegate { get; set; }

        // @property (nonatomic, weak) NSObject<DoSomthingClassDelegate> * delegate;
        [NullAllowed, Export("delegate", ArgumentSemantic.Weak)]
        NSObject WeakDelegate { get; set; }

        // -(void)doSomthingNew:(NSString *)from;
        [Export("doSomthingNew:")]
        void DoSomthingNew(string from);
    }
}

